### PR TITLE
Fix i18next unused keys when using self defined translation components

### LINKED ISSUE #22: False positive missing keys when using Trans from 'react-i18next'
Getting false positive missing keys when using Trans from 'react-i18next'.

Example:

```
<Text textStyle="body2">
	<TypeSafeTrans
		i18nKey="accounts:account.tabs.positions.table.footer.closeAll.modal.subtitle"
		components={[
			<Fragment key="0">
				<br />
				<br />
			</Fragment>,
		]}
	/>
</Text>
```

or

```
<Text textStyle="body2">
	<TypeSafeTrans
		i18nKey="account.tabs.positions.table.footer.closeAll.modal.subtitle"
                ns="accounts" // <- separated namespace
		components={[
			<Fragment key="0">
				<br />
				<br />
			</Fragment>,
		]}
	/>
</Text>
```

and running: `i18n-check -s en --locales public/locales -f i18next -u src -f i18next` gets `Found unused keys: account.tabs.positions.table.footer.closeAll.modal.subtitle`

Am I missing some configuration or is this not yet supported?

### PR DESCRIPTION
**Pull request by busypeoples**
Fixes `i18next` unused keys command when using self defined translation components. For example when a `Trans` component is wrapped in another component, the parser will skip checking for the key, which results in the key shown as not used.

```tsx
<WrappedTransComponent i18nKey="test.one">
  Welcome <b>{{ userName }}</b>, you can check for more information{" "}
  <a href="some-link">here</a>!
</WrappedTransComponent>
```

In that example the key `test.one` was identified as not used.

This change introduces the ` --parser-component-functions` to define all the additional component names that the i18next-parser should match.

Fixes #22

### CODE REVIEW

File: src/bin/index.ts [hunk 1]
```diff
@@ -1,60 +1,61 @@
...
-  )
-  .option(
-    "-f, --format [format type]",
+    "-f, --format <type>",
     "define the specific format: i18next or react-intl"
   )
   .option(
-    "-c, --check [checks]",
-    "define the specific checks you want to run: invalid, missing. By default the check will validate against missing and invalid keys, i.e. --check invalidKeys,missingKeys"
+    "-o, --only <only...>",
```
Comment (steos) [inline src/bin/index.ts:28]: Should we have some deprecation or something not to break existing users with this change?

**Review by steos — APPROVED** [review]

File: src/bin/index.ts (hunk 1 above)
Comment (busypeoples) [reply src/bin/index.ts:32]: Makes sense, updated with a deprecation notice.
